# to use container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
addons:
    apt:
        packages:
            - r-base
            - pandoc

before_install:
    # Tricks to avoid matplotlib error about X11:
    # 'no display name and no $DISPLAY environment variable'
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - pip install --upgrade pip
    - pip install -r dev_requirements.txt
    - pip install matplotlib
    - pip install weblogo
    - pip install jupyter ipython biopython # Stuff for the doc
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install "mdanalysis>=0.11"; fi

# command to run tests
script:
    - nosetests test_functions.py test_regression.py
    - yes | ./run_demo1_assignation.sh
    - yes | ./run_demo2_statistics.sh
    - yes | ./run_demo2_clusters.sh
    - cd doc-api; ./build.sh

#after_success:
