language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y r-base
    - pip install -r dev_requirements.txt --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install mdanalysis; fi
# command to run tests
script:
    - nosetests --with-coverage --cover-package=PBlib,PDBlib test_functions.py test_regression.py
    - yes | ./run_demo1.sh
    - yes | ./run_demo2.sh
#after_success:
